### ISSUE TITLE
Make won't finish correctly on macOS without NO_VULKAN=1 set

### ISSUE THREAD

**Issue by OleksiyPuzikov** [ColleagueRiley/RGFW#47]
```
glslangValidator -V examples/vk10/shaders/vert.vert -o examples/vk10/shaders/vert.h --vn vert_code
make: glslangValidator: No such file or directory
```

M1, Sequoia 15.1.1

**Comment by ColleagueRiley** [comment]
Since MacOS doesn't directly support Vulkan, I'm not sure if compiling the Vulkan example will work by default.

As for this specific issue, you will need to install the glslang compiler. I found one on brew https://formulae.brew.sh/formula/glslang, although there are reasons why you may not want to use it, Apple doesn't like users using Brew. But I'm unsure if there is an alternative. 

Thanks for filing this issue!

**Comment by OleksiyPuzikov** [comment]
Well, from my point of view Vulkan is not an official part of the macOS. I'd recommend to explicitly disable VULKAN flags and examples for Darwin and then enable them as needed based on environment variables etc, but that's totally up to you.

**Comment by ColleagueRiley** [comment]
@OleksiyPuzikov Isn't Vulkan already disabled by default?

**Comment by OleksiyPuzikov** [comment]
@ColleagueRiley No, it's on by default for Darwin, thus the ticket :)

**Comment by ColleagueRiley** [comment]
@OleksiyPuzikov I think this was set for MacOS, but the line got removed at some point. 

It should be fixed with this commit (https://github.com/ColleagueRiley/RGFW/commit/313f3ba4023ec3f026a906e909f9ad3de946e03c)

**Comment by OleksiyPuzikov** [comment]
This indeed fixes the issue.

While minor, this was somewhat inconvenient - thanks for the fast turnaround @ColleagueRiley and looking forward to other fixes at your convenience :)
