### ISSUE TITLE
Drag And Drop Causing Crash on X11

### ISSUE THREAD

**Issue by op4946** [ColleagueRiley/RGFW#50]
When testing Drag and drop with the RGFW_dnd event, I successfully got the files, but the program would crash immediately in the next RGFW_windowcheckEvent call.
My DND code is just this
```
case RGFW_dnd:
    printf("Got %d files\n", win->event.droppedFilesCount);
    for (u16 i = 0 ; i < win->event.droppedFilesCount ; i++) {
        printf("File %d: %s\n", i, win->event.droppedFiles[i]);
    }
    break;

```
Xorg logs this error:
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  25 (X_SendEvent)
  Value in failed request:  0x0
  Serial number of failed request:  2825
  Current serial number in output stream:  2825
```

After looking into it I noticed something weird with the code from here: ([https://github.com/ColleagueRiley/X11-Drag-n-Drop](https://github.com/ColleagueRiley/X11-Drag-n-Drop)).

> the drop has ended and XDnD versions 2 and older require the target to tell the source when the drop has ended

```
if (version >= 2) {
    reply.xclient.message_type = XdndFinished;
    reply.xclient.data.l[1] = result;
    reply.xclient.data.l[2] = XdndActionCopy;

    XSendEvent((Display*) display, source, False, NoEventMask, &reply);
    XFlush((Display*) display);
}
```
Versions 2 and older? But the condition works in the opposite way.
Switching the condition at the end of the `case SelectionNotify:` part of the eventHandler to:
`if (xdnd.version <= 2)`  (about line 3160 in my header version) fixes the problem for me, and I can get the files and continue on.

**Comment by ColleagueRiley** [comment]
@op4946 I believe this is a typo in the article rather than the code.

GLFW's code looks like this:

```c
                if (_glfw.x11.xdnd.version >= 2)
                {
                    XEvent reply = { ClientMessage };
                    reply.xclient.window = _glfw.x11.xdnd.source;
                    reply.xclient.message_type = _glfw.x11.XdndFinished;
                    reply.xclient.format = 32;
                    reply.xclient.data.l[0] = window->x11.handle;
                    reply.xclient.data.l[1] = result;
                    reply.xclient.data.l[2] = _glfw.x11.XdndActionCopy;

                    XSendEvent(_glfw.x11.display, _glfw.x11.xdnd.source,
                               False, NoEventMask, &reply);
                    XFlush(_glfw.x11.display);
                }
 ````
 
source (https://github.com/glfw/glfw/blob/21fea01161e0d6b70c0c5c1f52dc8e7a7df14a50/src/x11_window.c#L1720)

I'm not entirely sure why it has this error for you. I think there is a problem somewhere else in the code.

Do you know if the X11 example code from the tutorial works on your system? I don't have that error, but the example can help to find where the issue is. 

Thanks a lot for filing this issue!

**Comment by ColleagueRiley** [comment]
@op4946 Just a quick update, I just tested the `basic/basic` example and I get the same error. I wasn't getting this error before so it must be caused by something that changed now the last time I tested it.

**Comment by ColleagueRiley** [comment]
@op4946 This should be finished now with this commit. (https://github.com/ColleagueRiley/RGFW/commit/ef00e8fde3c73f1aeb3fa355370b8e5d73f671b3) 

The reason why changing the logic worked is because it didn't run this part of the code. However, that would lead to some issues with the X11 client because the `XdndFinish` reply is not being sent.  

I should also fix the wording in the tutorial, thanks for pointing this out!

**Comment by op4946** [comment]
I tested your fix on my computer, and everything now works. With a new clone of the repository, the examples like basic and callbacks all work fine (the examples had the same error before), and my code from before works as well.
