### ISSUE TITLE
Class.hIcon = LoadImageA(...) requires an explicit cast

### ISSUE THREAD

**Issue by dairin0d** [ColleagueRiley/RGFW#55]
When trying out RGFW, I ran into a compilation error on my PC (Windows 10, MinGW64): the compiler complains that HANDLE (returned by LoadImageA) cannot be implicitly cast into HICON (the type of Class.hIcon).

In case it might be relevant: I'm a newcomer when it comes to C/C++ ecosystem, but ChatGPT suggested that this could be due to a different Windows SDK version (mine seems to be 10.0, but perhaps in some versions the cast was allowed), or due to different strictness/permissiveness of compiler checks (I didn't use any special flags, so for me it's whatever MinGW / CMake / VS Code use by default).

**Comment by ColleagueRiley** [comment]
@dairin0d Thank you for filing this issue. I have a feeling it's due to a different MINGW distribution rather than a different Windows SDK version. Although I do not get this issue, I suppose it makes sense as the return type for `LoadImageA` is `HANDLE` rather than `HICON`, even though these types are essentially the same. 

This commit (https://github.com/ColleagueRiley/RGFW/commit/09ebe7dcb90fbd532f78cbaba68e85a49c8ccced) should fix the issue.

**Comment by dairin0d** [comment]
Thanks! Everything compiles now.
